EZBook/EZBook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ezbook_client.urls')),
    path('ezbook_admin/', include('ezbook_admin.urls'))
]

EZBook/ezbook_admin/urls.py
from django.urls import path, re_path, include
from ezbook_admin import views

app_name = 'ezbook_admin'

urlpatterns = [
    path('', views.dashboard, name="index"),
    path('tables/', include([
        re_path(r'^users/(?P<successRemarks>.*)?',
                views.Users.as_view(), name='users'),
        re_path(r'^companies/(?P<successRemarks>.*)?',
                views.Companies.as_view(), name='companies'),
        re_path(r'^drivers/(?P<successRemarks>.*)?',
                views.Drivers.as_view(), name='drivers'),
        re_path(r'^vehicles/(?P<successRemarks>.*)?',
                views.Vehicles.as_view(), name='vehicles'),
        re_path(r'^travelplaces/(?P<successRemarks>.*)?', views.Travelplaces.as_view(),
                name='travelplaces'),
        re_path(r'^bookings/(?P<successRemarks>.*)?',
                views.Bookings.as_view(), name='bookings'),
        re_path(r'^availablebookings/(?P<successRemarks>.*)?', views.Availablebookings.as_view(),
                name='availablebookings'),
    ]))
]

EZBook/ezbook_client/urls.py
from django.urls import path
from ezbook_client import views

app_name = 'ezbook_client'

urlpatterns = [
    path('', views.home, name='home'),
    path('features/', views.features, name='features'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signin/', views.signin, name='signin'),
    path('register/', views.register, name='register'),
]

EZBook/ezbook_admin/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    class Meta:
        db_table = "user"
    user_pic = models.CharField(
        max_length=100, default='noimage.png', null=False)
    username = models.CharField(max_length=100, default='', null=False)
    password = models.CharField(max_length=100, default='', null=False)
    firstname = models.CharField(max_length=100, default='', null=False)
    middlename = models.CharField(max_length=100, default='', null=False)
    lastname = models.CharField(max_length=100, default='', null=False)
    age = models.IntegerField()
    phone_number = models.CharField(max_length=100, default='', null=False)
    email = models.EmailField()
    date_created = models.DateField()


class Company(models.Model):
    class Meta:
        db_table = "company"
    username = models.CharField(max_length=100, default='', null=False)
    password = models.CharField(max_length=100, default='', null=False)
    name_company = models.CharField(max_length=100, default='', null=False)
    date_created = models.DateField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=100, default='', null=False)
    company_pic = models.CharField(
        max_length=100, default='noimage.png', null=False)


class Driver(models.Model):
    class Meta:
        db_table = "driver"
    driver_pic = models.CharField(
        max_length=100, default='noimage.png', null=False)
    driver_fullname = models.CharField(max_length=100, default='', null=False)
    company_name = models.ForeignKey(Company, on_delete=models.CASCADE)


class Vehicle(models.Model):
    class Meta:
        db_table = "vehicle"
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    vehicle_plate = models.CharField(max_length=100, default='', null=False)
    vehicle_driver_id = models.ForeignKey(Driver, on_delete=models.CASCADE)
    vehicle_capacity = models.IntegerField()
    vehicle_type = models.CharField(max_length=100, default='', null=False)
    vehicle_pic = models.CharField(
        max_length=100, default='noimage.png', null=False)


class Travel_Places(models.Model):
    class Meta:
        db_table = "travel_places"
    places = models.CharField(max_length=100, default='', null=False)


class BookTravel(models.Model):
    class Meta:
        db_table = "booktravel"
    vehicle_id = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    place_from = models.ForeignKey(
        Travel_Places, on_delete=models.CASCADE, related_name='places_from')
    place_to = models.ForeignKey(
        Travel_Places, on_delete=models.CASCADE, related_name='places_to')
    available_travel_date = models.DateField()
    available_travel_time = models.TimeField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)


class Booking(models.Model):
    class Meta:
        db_table = "booking"
    booking_date = models.DateField()
    seat_number = models.IntegerField()
    user_travel_id = models.ForeignKey(User, on_delete=models.CASCADE)
    book_travel_id = models.ForeignKey(BookTravel, on_delete=models.CASCADE)

EZBook/ezbook_admin/forms.py
from django import forms
from ezbook_admin.models import User, Company, Driver, Vehicle, Travel_Places, BookTravel, Booking


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'firstname',
            'middlename',
            'lastname',
            'age',
            'phone_number',
            'email',
        )
        labels = {
            'firstname': 'First Name',
            'middlename': 'Middle Name',
            'lastname': 'Last Name',
        }


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = (
            'username',
            'name_company',
            'email',
            'phone_number',
        )
        labels = {
            'name_company': 'Company Name',
        }


class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = (
            'driver_fullname',
            'company_name',
        )
        labels = {
            'driver_fullname': 'Driver Full Name',
        }


class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = (
            'vehicle_plate',
            'vehicle_driver_id',
            'vehicle_capacity',
            'vehicle_type',
            'company_id'
        )
        labels = {
            'vehicle_driver_id': 'Vehicle Driver',
            'company_id': 'Company'
        }


class Travel_PlacesForm(forms.ModelForm):
    class Meta:
        model = Travel_Places
        fields = ('places',)
        labels = {
            'places': 'Place'
        }


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = (
            'seat_number',
            'user_travel_id',
            'book_travel_id',
        )
        labels = {
            'user_travel_id': 'User',
            'book_travel_id': 'Travel Place',
        }


class BookTravelForm(forms.ModelForm):
    class Meta:
        model = BookTravel
        fields = (
            'vehicle_id',
            'place_from',
            'place_to',
            'available_travel_date',
            'available_travel_time',
            'company',
        )
        labels = {
            'vehicle_id': 'Vehicle',
            'available_travel_date': 'Travel date',
            'available_travel_time': 'Travel time',
        }
        widgets = {
            'available_travel_date': forms.DateInput(format="%m/%d/%Y", attrs={'type': 'date'}),
            'available_travel_time': forms.TimeInput(format="%H:%M", attrs={'type': 'time'})
        }

EZBook/ezbook_admin/views.py
from django.shortcuts import redirect, render
from django.views.generic import View
from ezbook_admin.models import User, Company, Driver, Vehicle, Travel_Places, BookTravel, Booking
from ezbook_admin.forms import UserForm, CompanyForm, DriverForm, VehicleForm, Travel_PlacesForm, BookTravelForm, BookingForm
from datetime import date, datetime
from django.core import serializers
import json

# Create your views here.

base_title = 'EZBook Admin'


def dashboard(request):
    count = {
        "user_count": User.objects.all().count(),
        "bookings_count": Booking.objects.all().count(),
        "company_count": Company.objects.all().count(),
        "driver_count": Driver.objects.all().count(),
        "vehicle_count": Vehicle.objects.all().count(),
    }

    data = Booking.objects.raw(
        "SELECT 1 as id, COUNT(ID) as total, booking_date FROM heroku_edd82c657812381.booking group by booking_date")

    date = []
    num = []
    for i in data:
        date.append((i.booking_date))
        num.append(i.total)

    return render(request, 'ezbook_admin/index.html', {'title': f'{base_title} - Dashboard', 'count': count, 'date': json.dumps(date, cls=serializers.json.DjangoJSONEncoder), 'num': json.dumps(num)})


class Users(View):
    title = 'Users'

    def get(self, request, *args, **kwargs):
        form = UserForm()
        users = User.objects.all()
        return render(request, 'ezbook_admin/tables/users.html', {'title': f'{base_title} - {self.title}', 'users': users, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = UserForm(request.POST)
        if request.POST.get('method') == 'delete':
            User.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:users',
                            successRemarks="User deleted successfully!")
        if form.is_valid():
            user = {
                'username': request.POST.get('username'),
                'firstname': request.POST.get('firstname'),
                'middlename': request.POST.get('middlename'),
                'lastname': request.POST.get('lastname'),
                'age': request.POST.get('age'),
                'phone_number': request.POST.get('phone_number'),
                'email': request.POST.get('email')
            }
            if request.POST.get('method') == 'insert':
                User(date_created=date.today(), **user).save()
                return redirect('ezbook_admin:users',
                                successRemarks="User added successfully!")
            elif request.POST.get('method') == 'update':
                User.objects.filter(pk=request.POST.get('pk')).update(**user)
                return redirect('ezbook_admin:users',
                                successRemarks="User updated successfully!")
        users = User.objects.all()
        return render(request, 'ezbook_admin/tables/users.html', {'title': f'{base_title} - {self.title}', 'users': users, 'form': form})


class Companies(View):
    title = 'Companies'

    def get(self, request, *args, **kwargs):
        form = CompanyForm()
        companies = Company.objects.all()
        return render(request, 'ezbook_admin/tables/companies.html', {'title': f'{base_title} - {self.title}', 'companies': companies, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = CompanyForm(request.POST)
        if request.POST.get('method') == 'delete':
            Company.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:companies',
                            successRemarks="Company deleted successfully!")
        if form.is_valid():
            company = {
                'username': request.POST.get('username'),
                'name_company': request.POST.get('name_company'),
                'email': request.POST.get('email'),
                'phone_number': request.POST.get('phone_number')
            }
            if request.POST.get('method') == 'insert':
                Company(date_created=date.today(), **company).save()
                return redirect('ezbook_admin:companies',
                                successRemarks="Company added successfully!")
            elif request.POST.get('method') == 'update':
                Company.objects.filter(
                    pk=request.POST.get('pk')).update(**company)
                return redirect('ezbook_admin:companies',
                                successRemarks="Company updated successfully!")
        companies = Company.objects.all()
        return render(request, 'ezbook_admin/tables/companies.html', {'title': f'{base_title} - {self.title}', 'companies': companies, 'form': form})


class Drivers(View):
    title = 'Drivers'

    def get(self, request, *args, **kwargs):
        form = DriverForm()
        drivers = Driver.objects.all()
        return render(request, 'ezbook_admin/tables/drivers.html', {'title': f'{base_title} - {self.title}', 'drivers': drivers, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = DriverForm(request.POST)
        if request.POST.get('method') == 'delete':
            Driver.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:drivers',
                            successRemarks="Driver deleted successfully!")
        if form.is_valid():
            driver = {
                'driver_fullname': request.POST.get('driver_fullname'),
                'company_name': Company.objects.get(id=request.POST.get('company_name'))
            }
            if request.POST.get('method') == 'insert':
                Driver(**driver).save()
                return redirect('ezbook_admin:drivers',
                                successRemarks="Driver added successfully!")
            elif request.POST.get('method') == 'update':
                Driver.objects.filter(
                    pk=request.POST.get('pk')).update(**driver)
                return redirect('ezbook_admin:drivers',
                                successRemarks="Driver updated successfully!")
        drivers = Driver.objects.all()
        return render(request, 'ezbook_admin/tables/drivers.html', {'title': f'{base_title} - {self.title}', 'drivers': drivers, 'form': form})


class Vehicles(View):
    title = 'Vehicles'

    def get(self, request, *args, **kwargs):
        form = VehicleForm()
        vehicles = Vehicle.objects.all()
        return render(request, 'ezbook_admin/tables/vehicles.html', {'title': f'{base_title} - {self.title}', 'vehicles': vehicles, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = VehicleForm(request.POST)
        if request.POST.get('method') == 'delete':
            Vehicle.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:vehicles',
                            successRemarks="Vehicle deleted successfully!")
        if form.is_valid():
            vehicle = {
                'vehicle_plate': request.POST.get('vehicle_plate'),
                'vehicle_driver_id': Driver.objects.get(id=request.POST.get('vehicle_driver_id')),
                'vehicle_capacity': request.POST.get('vehicle_capacity'),
                'vehicle_type': request.POST.get('vehicle_type'),
                'company_id': Company.objects.get(id=request.POST.get('company_id'))
            }
            if request.POST.get('method') == 'insert':
                Vehicle(**vehicle).save()
                return redirect('ezbook_admin:vehicles',
                                successRemarks="Vehicle added successfully!")
            elif request.POST.get('method') == 'update':
                Vehicle.objects.filter(
                    pk=request.POST.get('pk')).update(**vehicle)
                return redirect('ezbook_admin:vehicles',
                                successRemarks="Vehicle updated successfully!")
        vehicles = Vehicle.objects.all()
        return render(request, 'ezbook_admin/tables/vehicles.html', {'title': f'{base_title} - {self.title}', 'vehicles': vehicles, 'form': form})


class Travelplaces(View):
    title = 'Travel Places'

    def get(self, request, *args, **kwargs):
        form = Travel_PlacesForm()
        travel_places = Travel_Places.objects.all()
        return render(request, 'ezbook_admin/tables/travelplaces.html', {'title': f'{base_title} - {self.title}', 'travel_places': travel_places, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = Travel_PlacesForm(request.POST)
        if request.POST.get('method') == 'delete':
            Travel_Places.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:travelplaces',
                            successRemarks="Travel Place deleted successfully!")
        if form.is_valid():
            travel_place = {'places': request.POST.get('places')}
            if request.POST.get('method') == 'insert':
                Travel_Places(**travel_place).save()
                return redirect('ezbook_admin:travelplaces',
                                successRemarks="Travel Place added successfully!")
            elif request.POST.get('method') == 'update':
                Travel_Places.objects.filter(
                    pk=request.POST.get('pk')).update(**travel_place)
                return redirect('ezbook_admin:travelplaces',
                                successRemarks="Travel Place updated successfully!")
        travel_places = Travel_Places.objects.all()
        return render(request, 'ezbook_admin/tables/travelplaces.html', {'title': f'{base_title} - {self.title}', 'travel_places': travel_places, 'form': form})


class Bookings(View):
    title = 'Bookings'

EZBook/ezbook_admin/templates/ezbook_admin/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>{{title}}</title>

	<!-- ===============================================-->
	<!--    Stylesheets-->
	<!-- ===============================================-->

	<!-- Custom fonts for this template-->
	<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
	<link
		href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
		rel="stylesheet">

	<!-- Custom styles for this template-->
	<link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

	<!-- Bootstrap DataTables CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.11.2/css/dataTables.bootstrap4.min.css">

	<!-- ===============================================-->
	<!--    JavaScripts-->
	<!-- ===============================================-->

	<!-- Bootstrap core JavaScript-->
	<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

	<!-- Core plugin JavaScript-->
	<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

	<!-- Bootstrap DataTables JS -->
	<script src="https://cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.11.2/js/dataTables.bootstrap4.min.js"></script>
</head>

<body id="page-top">

	<!-- Page Wrapper -->
	<div id="wrapper" class="">

		<!-- Sidebar -->
		<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

			<!-- Sidebar - Brand -->
			<a class="sidebar-brand d-flex align-items-center justify-content-center"
				href="{% url 'ezbook_admin:index' %}">
				<div class="sidebar-brand-icon rotate-n-15">
					<i class="fas fa-laugh-wink"></i>
				</div>
				<div class="sidebar-brand-text mx-3">EZBook Admin</div>
			</a>

			<!-- Divider -->
			<hr class="sidebar-divider my-0">

			<!-- Nav Item - Dashboard -->
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'ezbook_admin:index' %}">
					<i class="fas fa-fw fa-tachometer-alt"></i>
					<span>Dashboard</span></a>
			</li>

			<!-- Divider -->
			<hr class="sidebar-divider">

			<!-- Heading -->
			<div class="sidebar-heading">Model Management</div>

			<!-- Nav Item - Pages Collapse Menu -->
			<li class="nav-item">
				<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
					aria-expanded="true" aria-controls="collapseTwo">
					<i class="fas fa-table"></i>
					<span>Table</span>
				</a>
				<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
					<div class="bg-white py-2 collapse-inner rounded">
						<h6 class="collapse-header">Tables:</h6>
						<a class="collapse-item" href="{% url 'ezbook_admin:users' %}">Users</a>
						<a class="collapse-item" href="{% url 'ezbook_admin:companies' %}">Companies</a>
						<a class="collapse-item" href="{% url 'ezbook_admin:drivers' %}">Drivers</a>
						<a class="collapse-item" href="{% url 'ezbook_admin:vehicles' %}">Vehicles</a>
						<a class="collapse-item" href="{% url 'ezbook_admin:travelplaces' %}">Travel Places</a>
						<a class="collapse-item" href="{% url 'ezbook_admin:bookings' %}">Bookings</a>
						<a class="collapse-item" href="{% url 'ezbook_admin:availablebookings' %}">Available
							Bookings</a>
					</div>
				</div>
			</li>

			<!-- Divider -->
			<hr class="sidebar-divider">

			<!-- Sidebar Toggler (Sidebar) -->
			<div class="text-center d-none d-md-inline">
				<button class="rounded-circle border-0" id="sidebarToggle"></button>
			</div>
		</ul>
		<!-- End of Sidebar -->

		<!-- Content Wrapper -->
		<div id="content-wrapper" class="d-flex flex-column">

			<!-- Main Content -->
			<div id="content">

				<!-- Topbar -->
				<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

					<!-- Sidebar Toggle (Topbar) -->
					<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
						<i class="fa fa-bars"></i>
					</button>

					<!-- Topbar Navbar -->
					<ul class="navbar-nav ml-auto">

						<!-- <li class="nav-item dropdown no-arrow mx-1">
							<a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
								data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="fas fa-bell fa-fw"></i>
								<span class="badge badge-danger badge-counter">3+</span>
							</a>
							<div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
								aria-labelledby="alertsDropdown">
								<h6 class="dropdown-header">
									Alerts Center
								</h6>
								<a class="dropdown-item d-flex align-items-center" href="#">
									<div class="mr-3">
										<div class="icon-circle bg-primary">
											<i class="fas fa-file-alt text-white"></i>
										</div>
									</div>
									<div>
										<div class="small text-gray-500">December 12, 2019</div>
										<span class="font-weight-bold">A new monthly report is ready to download!</span>
									</div>
								</a>
								<a class="dropdown-item d-flex align-items-center" href="#">
									<div class="mr-3">
										<div class="icon-circle bg-success">
											<i class="fas fa-donate text-white"></i>
										</div>
									</div>
									<div>
										<div class="small text-gray-500">December 7, 2019</div>
										$290.29 has been deposited into your account!
									</div>
								</a>
								<a class="dropdown-item d-flex align-items-center" href="#">
									<div class="mr-3">
										<div class="icon-circle bg-warning">
											<i class="fas fa-exclamation-triangle text-white"></i>
										</div>
									</div>
									<div>
										<div class="small text-gray-500">December 2, 2019</div>
										Spending Alert: We've noticed unusually high spending for your account.
									</div>
								</a>
								<a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
							</div>
						</li>

						<li class="nav-item dropdown no-arrow mx-1">
							<a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
								data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="fas fa-envelope fa-fw"></i>
								<span class="badge badge-danger badge-counter">7</span>
							</a>
							<div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
								aria-labelledby="messagesDropdown">
								<h6 class="dropdown-header">
									Message Center
								</h6>
								<a class="dropdown-item d-flex align-items-center" href="#">
									<div class="dropdown-list-image mr-3">
										<img class="rounded-circle" src="{% static 'img/undraw_profile_1.svg' %}"
											alt="...">
										<div class="status-indicator bg-success"></div>
									</div>
									<div class="font-weight-bold">
										<div class="text-truncate">Hi there! I am wondering if you can help me with a
											problem I've been having.</div>
										<div class="small text-gray-500">Emily Fowler · 58m</div>
									</div>
								</a>
								<a class="dropdown-item d-flex align-items-center" href="#">
									<div class="dropdown-list-image mr-3">
										<img class="rounded-circle" src="{% static 'img/undraw_profile_2.svg' %}"
											alt="...">
										<div class="status-indicator"></div>
									</div>
									<div>
										<div class="text-truncate">I have the photos that you ordered last month, how
											would you like them sent to you?</div>
										<div class="small text-gray-500">Jae Chun · 1d</div>
									</div>
								</a>
								<a class="dropdown-item d-flex align-items-center" href="#">
									<div class="dropdown-list-image mr-3">
										<img class="rounded-circle" src="{% static 'img/undraw_profile_3.svg' %}"
											alt="...">
										<div class="status-indicator bg-warning"></div>
									</div>
									<div>
										<div class="text-truncate">Last month's report looks great, I am very happy with
											the progress so far, keep up the good work!</div>
										<div class="small text-gray-500">Morgan Alvarez · 2d</div>
									</div>
								</a>
								<a class="dropdown-item d-flex align-items-center" href="#">
									<div class="dropdown-list-image mr-3">
										<img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
											alt="...">
										<div class="status-indicator bg-success"></div>
									</div>
									<div>
										<div class="text-truncate">Am I a good boy? The reason I ask is because someone
											told me that people say this to all dogs, even if they aren't good...</div>
										<div class="small text-gray-500">Chicken the Dog · 2w</div>
									</div>
								</a>
								<a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
							</div>
						</li>

						<div class="topbar-divider d-none d-sm-block"></div> -->

						<!-- Nav Item - User Information -->
						<li class="nav-item dropdown no-arrow">
							<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
								data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<span class="mr-2 d-none d-lg-inline text-gray-600 small">John Doe</span>
								<img class="img-profile rounded-circle" src="{% static 'img/undraw_p' %}rofile.svg">
							</a>
							<!-- Dropdown - User Information -->
							<div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
								aria-labelledby="userDropdown">
								<a class="dropdown-item" href="#">
									<i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
									Profile
								</a>
								<a class="dropdown-item" href="#">
									<i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
									Settings
								</a>
								<a class="dropdown-item" href="#">
									<i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
									Activity Log
								</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
									<i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
									Logout
								</a>
							</div>
						</li>

					</ul>

				</nav>
				<!-- End of Topbar -->

				<!-- Begin Page Content -->
				{% block content %}{% endblock %}
			</div>
			<!-- End of Main Content -->

			<!-- Footer -->
			<footer class="sticky-footer bg-white">
				<div class="container my-auto">
					<div class="copyright text-center my-auto">
						<span>Copyright &copy; EZBook 2021</span>
					</div>
					<br />
					<div class="copyright text-center my-auto">
						<a href="{% url 'ezbook_client:home' %}" style="color: black;"><span>EZBook Client</span></a>
					</div>
				</div>
			</footer>
			<!-- End of Footer -->

		</div>
		<!-- End of Content Wrapper -->

	</div>
	<!-- End of Page Wrapper -->

	<!-- Scroll to Top Button-->
	<a class="scroll-to-top rounded" href="#page-top">
		<i class="fas fa-angle-up"></i>
	</a>

	<!-- Logout Modal-->
	<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
		aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
					<button class="close" type="button" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
				<div class="modal-footer">
					<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
					<a class="btn btn-primary" href="login.html">Logout</a>
				</div>
			</div>
		</div>
	</div>

	<!-- Custom scripts for all pages-->
	<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
</body>

</html>