EZBook/EZBook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ezbook_client.urls')),
    path('ezbook_admin/', include('ezbook_admin.urls'))
]

EZBook/ezbook_admin/urls.py
from django.urls import path, re_path, include
from ezbook_admin import views

app_name = 'ezbook_admin'

urlpatterns = [
    path('', views.dashboard, name="index"),
    path('tables/', include([
        re_path(r'^users/(?P<successRemarks>.*)?',
                views.Users.as_view(), name='users'),
        re_path(r'^companies/(?P<successRemarks>.*)?',
                views.Companies.as_view(), name='companies'),
        re_path(r'^drivers/(?P<successRemarks>.*)?',
                views.Drivers.as_view(), name='drivers'),
        re_path(r'^vehicles/(?P<successRemarks>.*)?',
                views.Vehicles.as_view(), name='vehicles'),
        re_path(r'^travelplaces/(?P<successRemarks>.*)?', views.Travelplaces.as_view(),
                name='travelplaces'),
        re_path(r'^bookings/(?P<successRemarks>.*)?',
                views.Bookings.as_view(), name='bookings'),
        re_path(r'^availablebookings/(?P<successRemarks>.*)?', views.Availablebookings.as_view(),
                name='availablebookings'),
    ]))
]

EZBook/ezbook_admin/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    class Meta:
        db_table = "user"
    user_pic = models.CharField(
        max_length=100, default='noimage.png', null=False)
    username = models.CharField(max_length=100, default='', null=False)
    password = models.CharField(max_length=100, default='', null=False)
    firstname = models.CharField(max_length=100, default='', null=False)
    middlename = models.CharField(max_length=100, default='', null=False)
    lastname = models.CharField(max_length=100, default='', null=False)
    age = models.IntegerField()
    phone_number = models.CharField(max_length=100, default='', null=False)
    email = models.EmailField()
    date_created = models.DateField()


class Company(models.Model):
    class Meta:
        db_table = "company"
    username = models.CharField(max_length=100, default='', null=False)
    password = models.CharField(max_length=100, default='', null=False)
    name_company = models.CharField(max_length=100, default='', null=False)
    date_created = models.DateField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=100, default='', null=False)
    company_pic = models.CharField(
        max_length=100, default='noimage.png', null=False)


class Driver(models.Model):
    class Meta:
        db_table = "driver"
    driver_pic = models.CharField(
        max_length=100, default='noimage.png', null=False)
    driver_fullname = models.CharField(max_length=100, default='', null=False)
    company_name = models.ForeignKey(Company, on_delete=models.CASCADE)


class Vehicle(models.Model):
    class Meta:
        db_table = "vehicle"
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    vehicle_plate = models.CharField(max_length=100, default='', null=False)
    vehicle_driver_id = models.ForeignKey(Driver, on_delete=models.CASCADE)
    vehicle_capacity = models.IntegerField()
    vehicle_type = models.CharField(max_length=100, default='', null=False)
    vehicle_pic = models.CharField(
        max_length=100, default='noimage.png', null=False)


class Travel_Places(models.Model):
    class Meta:
        db_table = "travel_places"
    places = models.CharField(max_length=100, default='', null=False)


class BookTravel(models.Model):
    class Meta:
        db_table = "booktravel"
    vehicle_id = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    place_from = models.ForeignKey(
        Travel_Places, on_delete=models.CASCADE, related_name='places_from')
    place_to = models.ForeignKey(
        Travel_Places, on_delete=models.CASCADE, related_name='places_to')
    available_travel_date = models.DateField()
    available_travel_time = models.TimeField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)


class Booking(models.Model):
    class Meta:
        db_table = "booking"
    booking_date = models.DateField()
    seat_number = models.IntegerField()
    user_travel_id = models.ForeignKey(User, on_delete=models.CASCADE)
    book_travel_id = models.ForeignKey(BookTravel, on_delete=models.CASCADE)

EZBook/ezbook_admin/forms.py
from django import forms
from ezbook_admin.models import User, Company, Driver, Vehicle, Travel_Places, BookTravel, Booking


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'firstname',
            'middlename',
            'lastname',
            'age',
            'phone_number',
            'email',
        )
        labels = {
            'firstname': 'First Name',
            'middlename': 'Middle Name',
            'lastname': 'Last Name',
        }


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = (
            'username',
            'name_company',
            'email',
            'phone_number',
        )
        labels = {
            'name_company': 'Company Name',
        }


class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = (
            'driver_fullname',
            'company_name',
        )
        labels = {
            'driver_fullname': 'Driver Full Name',
        }


class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = (
            'vehicle_plate',
            'vehicle_driver_id',
            'vehicle_capacity',
            'vehicle_type',
            'company_id'
        )
        labels = {
            'vehicle_driver_id': 'Vehicle Driver',
            'company_id': 'Company'
        }


class Travel_PlacesForm(forms.ModelForm):
    class Meta:
        model = Travel_Places
        fields = ('places',)
        labels = {
            'places': 'Place'
        }


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = (
            'seat_number',
            'user_travel_id',
            'book_travel_id',
        )
        labels = {
            'user_travel_id': 'User',
            'book_travel_id': 'Travel Place',
        }


class BookTravelForm(forms.ModelForm):
    class Meta:
        model = BookTravel
        fields = (
            'vehicle_id',
            'place_from',
            'place_to',
            'available_travel_date',
            'available_travel_time',
            'company',
        )
        labels = {
            'vehicle_id': 'Vehicle',
            'available_travel_date': 'Travel date',
            'available_travel_time': 'Travel time',
        }
        widgets = {
            'available_travel_date': forms.DateInput(format="%m/%d/%Y", attrs={'type': 'date'}),
            'available_travel_time': forms.TimeInput(format="%H:%M", attrs={'type': 'time'})
        }

EZBook/ezbook_admin/views.py
from django.shortcuts import redirect, render
from django.views.generic import View
from ezbook_admin.models import User, Company, Driver, Vehicle, Travel_Places, BookTravel, Booking
from ezbook_admin.forms import UserForm, CompanyForm, DriverForm, VehicleForm, Travel_PlacesForm, BookTravelForm, BookingForm
from datetime import date, datetime
from django.core import serializers
import json

# Create your views here.

base_title = 'EZBook Admin'


def dashboard(request):
    count = {
        "user_count": User.objects.all().count(),
        "bookings_count": Booking.objects.all().count(),
        "company_count": Company.objects.all().count(),
        "driver_count": Driver.objects.all().count(),
        "vehicle_count": Vehicle.objects.all().count(),
    }

    data = Booking.objects.raw(
        "SELECT 1 as id, COUNT(ID) as total, booking_date FROM heroku_edd82c657812381.booking group by booking_date")

    date = []
    num = []
    for i in data:
        date.append((i.booking_date))
        num.append(i.total)

    return render(request, 'ezbook_admin/index.html', {'title': f'{base_title} - Dashboard', 'count': count, 'date': json.dumps(date, cls=serializers.json.DjangoJSONEncoder), 'num': json.dumps(num)})


class Users(View):
    title = 'Users'

    def get(self, request, *args, **kwargs):
        form = UserForm()
        users = User.objects.all()
        return render(request, 'ezbook_admin/tables/users.html', {'title': f'{base_title} - {self.title}', 'users': users, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = UserForm(request.POST)
        if request.POST.get('method') == 'delete':
            User.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:users',
                            successRemarks="User deleted successfully!")
        if form.is_valid():
            user = {
                'username': request.POST.get('username'),
                'firstname': request.POST.get('firstname'),
                'middlename': request.POST.get('middlename'),
                'lastname': request.POST.get('lastname'),
                'age': request.POST.get('age'),
                'phone_number': request.POST.get('phone_number'),
                'email': request.POST.get('email')
            }
            if request.POST.get('method') == 'insert':
                User(date_created=date.today(), **user).save()
                return redirect('ezbook_admin:users',
                                successRemarks="User added successfully!")
            elif request.POST.get('method') == 'update':
                User.objects.filter(pk=request.POST.get('pk')).update(**user)
                return redirect('ezbook_admin:users',
                                successRemarks="User updated successfully!")
        users = User.objects.all()
        return render(request, 'ezbook_admin/tables/users.html', {'title': f'{base_title} - {self.title}', 'users': users, 'form': form})


class Companies(View):
    title = 'Companies'

    def get(self, request, *args, **kwargs):
        form = CompanyForm()
        companies = Company.objects.all()
        return render(request, 'ezbook_admin/tables/companies.html', {'title': f'{base_title} - {self.title}', 'companies': companies, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = CompanyForm(request.POST)
        if request.POST.get('method') == 'delete':
            Company.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:companies',
                            successRemarks="Company deleted successfully!")
        if form.is_valid():
            company = {
                'username': request.POST.get('username'),
                'name_company': request.POST.get('name_company'),
                'email': request.POST.get('email'),
                'phone_number': request.POST.get('phone_number')
            }
            if request.POST.get('method') == 'insert':
                Company(date_created=date.today(), **company).save()
                return redirect('ezbook_admin:companies',
                                successRemarks="Company added successfully!")
            elif request.POST.get('method') == 'update':
                Company.objects.filter(
                    pk=request.POST.get('pk')).update(**company)
                return redirect('ezbook_admin:companies',
                                successRemarks="Company updated successfully!")
        companies = Company.objects.all()
        return render(request, 'ezbook_admin/tables/companies.html', {'title': f'{base_title} - {self.title}', 'companies': companies, 'form': form})


class Drivers(View):
    title = 'Drivers'

    def get(self, request, *args, **kwargs):
        form = DriverForm()
        drivers = Driver.objects.all()
        return render(request, 'ezbook_admin/tables/drivers.html', {'title': f'{base_title} - {self.title}', 'drivers': drivers, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = DriverForm(request.POST)
        if request.POST.get('method') == 'delete':
            Driver.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:drivers',
                            successRemarks="Driver deleted successfully!")
        if form.is_valid():
            driver = {
                'driver_fullname': request.POST.get('driver_fullname'),
                'company_name': Company.objects.get(id=request.POST.get('company_name'))
            }
            if request.POST.get('method') == 'insert':
                Driver(**driver).save()
                return redirect('ezbook_admin:drivers',
                                successRemarks="Driver added successfully!")
            elif request.POST.get('method') == 'update':
                Driver.objects.filter(
                    pk=request.POST.get('pk')).update(**driver)
                return redirect('ezbook_admin:drivers',
                                successRemarks="Driver updated successfully!")
        drivers = Driver.objects.all()
        return render(request, 'ezbook_admin/tables/drivers.html', {'title': f'{base_title} - {self.title}', 'drivers': drivers, 'form': form})


class Vehicles(View):
    title = 'Vehicles'

    def get(self, request, *args, **kwargs):
        form = VehicleForm()
        vehicles = Vehicle.objects.all()
        return render(request, 'ezbook_admin/tables/vehicles.html', {'title': f'{base_title} - {self.title}', 'vehicles': vehicles, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = VehicleForm(request.POST)
        if request.POST.get('method') == 'delete':
            Vehicle.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:vehicles',
                            successRemarks="Vehicle deleted successfully!")
        if form.is_valid():
            vehicle = {
                'vehicle_plate': request.POST.get('vehicle_plate'),
                'vehicle_driver_id': Driver.objects.get(id=request.POST.get('vehicle_driver_id')),
                'vehicle_capacity': request.POST.get('vehicle_capacity'),
                'vehicle_type': request.POST.get('vehicle_type'),
                'company_id': Company.objects.get(id=request.POST.get('company_id'))
            }
            if request.POST.get('method') == 'insert':
                Vehicle(**vehicle).save()
                return redirect('ezbook_admin:vehicles',
                                successRemarks="Vehicle added successfully!")
            elif request.POST.get('method') == 'update':
                Vehicle.objects.filter(
                    pk=request.POST.get('pk')).update(**vehicle)
                return redirect('ezbook_admin:vehicles',
                                successRemarks="Vehicle updated successfully!")
        vehicles = Vehicle.objects.all()
        return render(request, 'ezbook_admin/tables/vehicles.html', {'title': f'{base_title} - {self.title}', 'vehicles': vehicles, 'form': form})


class Travelplaces(View):
    title = 'Travel Places'

    def get(self, request, *args, **kwargs):
        form = Travel_PlacesForm()
        travel_places = Travel_Places.objects.all()
        return render(request, 'ezbook_admin/tables/travelplaces.html', {'title': f'{base_title} - {self.title}', 'travel_places': travel_places, 'form': form, 'successRemarks': kwargs['successRemarks']})

    def post(self, request, *args, **kwargs):
        form = Travel_PlacesForm(request.POST)
        if request.POST.get('method') == 'delete':
            Travel_Places.objects.filter(pk=request.POST.get('pk')).delete()
            return redirect('ezbook_admin:travelplaces',
                            successRemarks="Travel Place deleted successfully!")
        if form.is_valid():
            travel_place = {'places': request.POST.get('places')}
            if request.POST.get('method') == 'insert':
                Travel_Places(**travel_place).save()
                return redirect('ezbook_admin:travelplaces',
                                successRemarks="Travel Place added successfully!")
            elif request.POST.get('method') == 'update':
                Travel_Places.objects.filter(
                    pk=request.POST.get('pk')).update(**travel_place)
                return redirect('ezbook_admin:travelplaces',
                                successRemarks="Travel Place updated successfully!")
        travel_places = Travel_Places.objects.all()
        return render(request, 'ezbook_admin/tables/travelplaces.html', {'title': f'{base_title} - {self.title}', 'travel_places': travel_places, 'form': form})


class Bookings(View):
    title = 'Bookings'

EZBook/ezbook_admin/templates/ezbook_admin/tables/availablebookings.html
{% extends 'ezbook_admin/base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
{% load json_str %}
<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">Available Bookings</h1>

  {% if form.errors %}
  <script type="text/javascript">
    $(() => {
      $('#addModal').modal('show');
    });
  </script>
  {% endif %}
  {% if successRemarks %}
  <div class="alert alert-success" role="alert">
    {{successRemarks}}
  </div>
  {% endif %}

  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3 d-flex justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">
        Available Bookings Table
      </h6>
      <p data-placement="top" data-toggle="tooltip" title="Add">
        <a href="" class="btn btn-success btn-xs" data-title="Add" data-toggle="modal" data-target="#addModal">
          <span class="fas fa-plus"></span>
        </a>
      </p>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-bordered" width="100%">
          <thead>
            <th>Available Travel Date</th>
            <th>Available Travel Time</th>
            <th>Company ID</th>
            <th>Place From</th>
            <th>Place To</th>
            <!-- <th>Vehicle ID</th> -->
            <th>Actions</th>
          </thead>
          <tbody>
            {% for available_booking in available_bookings %}
            <tr>
              <td>{{ available_booking.available_travel_date }}</td>
              <td>{{ available_booking.available_travel_time }}</td>
              <td>{{ available_booking.company_id }}</td>
              <td>{{ available_booking.place_from_id }}</td>
              <td>{{ available_booking.place_to_id }}</td>
              <!-- <td>{{ available_booking.vehicle_id_id }}</td> -->
              <td class="d-flex" style="gap: 5px">
                <p data-placement="top" data-toggle="tooltip" title="Edit">
                  <a class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#editModal"
                    onclick="onEditClick(this)" data-user='{{available_booking|json_str}}'>
                    <span class="fas fa-pen"></span>
                  </a>
                </p>
                <p data-placement="top" data-toggle="tooltip" title="Delete">
                  <a class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#deleteModal"
                    onclick='onDeleteClick(this)' data-user='{{available_booking|json_str}}'>
                    <span class="fas fa-trash-alt"></span>
                  </a>
                </p>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addModalLabel">Add Available Booking</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <form id="addSubmit" class="needs-validation" action="{% url 'ezbook_admin:availablebookings' %}" method="post"
        enctype="multipart/form-data" novalidate>
        {% csrf_token%}
        <div class="modal-body">
          <div class="row g-3">
            <div class="col-md-6">
              <!-- <label for="validationCustom00" class="form-label">Travel From</label>
              <input type="text" class="form-control" id="validationCustom00" required>
              <div class="invalid-feedback">
                Please provide a company name.
              </div> -->
              {{form.vehicle_id|as_crispy_field}}
            </div>
            <div class="col-md-6">
              <!-- <label for="validationCustom00" class="form-label">Travel To</label>
              <input type="text" class="form-control" id="validationCustom00" required>
              <div class="invalid-feedback">
                Please provide a company name.
              </div> -->
              {{form.company|as_crispy_field}}
            </div>
            <div class="col-md-6">
              <!-- <label for="validationCustom00" class="form-label">Travel Date</label>
              <input type="text" class="form-control" id="validationCustom00" required>
              <div class="invalid-feedback">
                Please provide a company name.
              </div> -->
              {{form.place_from|as_crispy_field}}
            </div>
            <div class="col-md-6">
              <!-- <label for="validationCustom04" class="form-label">Travel Time</label>
              <input type="text" class="form-control" id="validationCustom04" required>
              <div class="invalid-feedback">
                Please provide a phone number.
              </div> -->
              {{form.place_to|as_crispy_field}}
            </div>
            <div class="col-md-6">
              <!-- <label for="validationCustom05" class="form-label">Travel Company</label>
              <input type="email" class="form-control" id="validationCustom05" required>
              <div class="invalid-feedback">
                Please provide a valid email.
              </div> -->
              {{form.available_travel_date|as_crispy_field}}
            </div>
            <div class="col-md-6">
              <!-- <label for="validationCustom00" class="form-label">Travel Vehicle</label>
              <input type="text" class="form-control" id="validationCustom00" required>
              <div class="invalid-feedback">
                Please provide a company name.
              </div> -->
              {{form.available_travel_time|as_crispy_field}}
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" type="submit" name="method" value="insert">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit User</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <form id="editSubmit" class="needs-validation" action="{% url 'ezbook_admin:availablebookings' %}" method="post"
        enctype="multipart/form-data" novalidate>
        {% csrf_token%}
        <div class="modal-body">
          <div class="row g-3">
            <input type="hidden" id="pk" name="pk" />
            <div class="col-md-6">
              {{form.vehicle_id|as_crispy_field}}
            </div>
            <div class="col-md-6">
              {{form.company|as_crispy_field}}
            </div>
            <div class="col-md-6">
              {{form.place_from|as_crispy_field}}
            </div>
            <div class="col-md-6">
              {{form.place_to|as_crispy_field}}
            </div>
            <div class="col-md-6">
              {{form.available_travel_date|as_crispy_field}}
            </div>
            <div class="col-md-6">
              {{form.available_travel_time|as_crispy_field}}
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" type="submit" name="method" value="update">Update</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
  aria-hidden="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete User</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <form id="deleteSubmit" action="{% url 'ezbook_admin:availablebookings' %}" method="post"
        enctype="multipart/form-data" novalidate>
        {% csrf_token%}
        <input type="hidden" id="pk" name="pk" />
        <div class="modal-body" id="body">
          Are you sure you want to delete this user?
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" type="submit" name="method" value="delete">Confirm</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script type="text/javascript">
  function onEditClick(element) {
    const user = JSON.parse($(element).attr('data-user'))[0]
    if (!user) return;
    $('#editModal #pk').val(user.pk);
    $('#editModal #id_vehicle_id').val(user.fields.vehicle_id);
    $('#editModal #id_company').val(user.fields.company);
    $('#editModal #id_place_from').val(user.fields.place_from);
    $('#editModal #id_place_to').val(user.fields.place_to);
    $('#editModal #id_available_travel_date').val(user.fields.available_travel_date);
    $('#editModal #id_available_travel_time').val(user.fields.available_travel_time);
  }
  function onDeleteClick(element) {
    const user = JSON.parse($(element).attr('data-user'))[0]
    if (!user) return;
    $('#deleteModal #pk').val(user.pk);
    $('#deleteModal #body').html(`Are you sure you want to delete this?`);
  }
  $(() => {
    $('#bootstrapdatatable').DataTable({
      "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
      "iDisplayLength": 3,
      dom: 'Blfrtip',
      buttons: [
        'copy', 'csv', 'excel', 'pdf', 'print'
      ]
    }
    );
  });
</script>
{% endblock %}