EZBook/EZBook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ezbook_client.urls')),
    path('ezbook_admin/', include('ezbook_admin.urls'))
]

EZBook/ezbook_admin/urls.py
from django.urls import path, re_path, include
from ezbook_admin import views

app_name = 'ezbook_admin'

urlpatterns = [
    path('', views.dashboard, name="index"),
    path('tables/', include([
        re_path(r'^users/(?P<successRemarks>.*)?',
                views.Users.as_view(), name='users'),
        re_path(r'^companies/(?P<successRemarks>.*)?',
                views.Companies.as_view(), name='companies'),
        re_path(r'^drivers/(?P<successRemarks>.*)?',
                views.Drivers.as_view(), name='drivers'),
        re_path(r'^vehicles/(?P<successRemarks>.*)?',
                views.Vehicles.as_view(), name='vehicles'),
        re_path(r'^travelplaces/(?P<successRemarks>.*)?', views.Travelplaces.as_view(),
                name='travelplaces'),
        re_path(r'^bookings/(?P<successRemarks>.*)?',
                views.Bookings.as_view(), name='bookings'),
        re_path(r'^availablebookings/(?P<successRemarks>.*)?', views.Availablebookings.as_view(),
                name='availablebookings'),
    ]))
]

EZBook/ezbook_client/urls.py
from django.urls import path
from ezbook_client import views

app_name = 'ezbook_client'

urlpatterns = [
    path('', views.home, name='home'),
    path('features/', views.features, name='features'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signin/', views.signin, name='signin'),
    path('register/', views.register, name='register'),
]

EZBook/ezbook_client/models.py
from django.db import models

# Create your models here.

EZBook/ezbook_client/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.


def home(request):
    return render(request, 'ezbook_client/home.html')


def about(request):
    return render(request, 'ezbook_client/about.html', {'title': 'about'})


def features(request):
    return render(request, 'ezbook_client/features.html', {'title': 'features'})


def signin(request):
    return render(request, 'ezbook_client/signin.html', {'title': 'signin'})


def register(request):
    return render(request, 'ezbook_client/register.html', {'title': 'register'})


def contact(request):
    return render(request, 'ezbook_client/contact.html', {'title': 'contact'})

EZBook/ezbook_client/templates/ezbook_client/about.html
{% extends "ezbook_client/base.html" %} {% block content %}
<section>

  <div class="bg-light">
    <div class="container py-5">
      <div class="row h-100 align-items-center py-5">
        <div class="col-lg-6">
          <h1 class="display-4">About us</h1>
          <p class="lead text-muted mb-0">
            EZBook is an online web applications that aims to digitalize the
            booking of van and bus seats and to promote less hassle and paper-free
            transaction.
          </p>
        </div>
        <div class="col-lg-6 d-none d-lg-block">
          <img src="https://res.cloudinary.com/mhmd/image/upload/v1556834136/illus_kftyh4.png" alt=""
            class="img-fluid" />
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

EZBook/ezbook_client/templates/ezbook_client/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en-US" dir="ltr">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <!-- ===============================================-->
  <!--    Document Title-->
  <!-- ===============================================-->
  <title>EZBook</title>

  <!-- ===============================================-->
  <!--    Favicons-->
  <!-- ===============================================-->

  <link rel="manifest" href="{% static 'assets/img/favicons/manifest.json'%}" />

  <meta name="theme-color" content="#ffffff" />

  <!-- ===============================================-->
  <!--    Stylesheets-->
  <!-- ===============================================-->
  <link href="{% static 'assets/css/theme.css' %}" type="text/css" rel="stylesheet" />
  <link
    href="https://fonts.googleapis.com/css2?family=Exo+2:wght@200;300;400;500;600;700&amp;family=Montserrat:wght@200;300&amp;display=swap"
    rel="stylesheet" />
  <link
    href="https://fonts.googleapis.com/css2?family=Exo+2:wght@200;300;400;500;600;700&amp;family=Montserrat:wght@200;300;400;500;600;700&amp;display=swap"
    rel="stylesheet" />
</head>

<body>
  <!-- ===============================================-->
  <!--    Main Content-->
  <!-- ===============================================-->
  <main class="main" id="top">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-white py-3 d-block"
      data-navbar-on-scroll="data-navbar-on-scroll">
      <div class="container">
        <h1 style="color:blue">EZBook</h1>
        </a>
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto pt-2 pt-lg-0 font-base">
            <li class="nav-item px-2">
              <a class="nav-link fw-bold active" aria-current="page" href="{% url 'ezbook_client:home' %}">Home</a>
            </li>
            <li class="nav-item px-2">
              <a class="nav-link fw-bold" href="{% url 'ezbook_client:features' %}">Features</a>
            </li>
            <li class="nav-item px-2">
              <a class="nav-link fw-bold" href="{% url 'ezbook_client:about' %}">About us</a>
            </li>
            <li class="nav-item px-2">
              <a class="nav-link fw-bold" href="{% url 'ezbook_client:contact' %}">Contact us</a>
            </li>
          </ul>
          <form class="ps-lg-5">
            <a href="{% url 'ezbook_client:signin' %}">
              <button class="btn btn-link text-danger fw-bold order-1 order-lg-0" type="button">
                Sign in</button></a>
            <a class="btn hover-top btn-collab" href="{% url 'ezbook_client:register' %}">Register</a>
          </form>
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
    {% include 'ezbook_client/footer.html' %}
  </main>
  <!-- ===============================================-->
  <!--    End of Main Content-->
  <!-- ===============================================-->

  <!-- ===============================================-->
  <!--    JavaScripts-->
  <!-- ===============================================-->
  <script src="{% static 'vendors/@popperjs/popper.min.js' %}"></script>
  <script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
  <script src="{% static 'vendors/is/is.min.js' %}"></script>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
  <script src="{% static 'vendors/fontawesome/all.min.js' %}"></script>
  <script src="{% static 'assets/js/theme.js' %}"></script>
</body>

</html>

EZBook/ezbook_client/templates/ezbook_client/contact.html
{% extends "ezbook_client/base.html" %} {% block content %}
<section>

  <div class="bg-light">
    <div class="container py-5">
      <div class="row h-100 align-items-center py-5">
        <div class="col-lg-6">
          <h1 class="display-4">Contact us</h1>
          <p class="text mb-0">
            Phone: 09503587264
            <br>
            Address: Cebu City, Cebu
            <br>
            Email: ezbook@gmail.com
          </p>
        </div>
        <div class="col-lg-6 d-none d-lg-block">
          <img src="https://res.cloudinary.com/mhmd/image/upload/v1556834136/illus_kftyh4.png" alt=""
            class="img-fluid" />
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

EZBook/ezbook_client/templates/ezbook_client/features.html
{% extends "ezbook_client/base.html" %} {% load static %} {% block content %}

<section class="py-6">
  <div class="container">
    <div class="row flex-center">
      <center>
        <br />
        <br />
        <br />
        <h1>Features</h1>
      </center>
      <div class="col-md-4 col-lg-3 mt-4 mt-lg-8 text-center text-md-start">
        <div class="badge bg-soft-danger p-3 rounded-3">
          <img class="w-100 h-100" src="{% static 'assets/img/icons/edit.svg' %}" alt="..." />
        </div>
        <h4 class="mt-5 mb-3 fw-bold">Instant Booking</h4>
        <p class="fs-1 lh-sm">Book Anytime, Anywhere</p>
      </div>
      <div class="col-md-4 col-lg-3 mt-4 mt-lg-8 text-center text-md-start">
        <div class="badge bg-soft-danger p-3 rounded-3">
          <img class="w-100 h-100" src="{% static 'assets/img/icons/monitor.svg' %}" alt="..." />
        </div>
        <h4 class="mt-5 mb-3 fw-bold">Easy access</h4>
        <p class="fs-1 lh-sm">
          Can easily access different travel destinations<br class="d-none d-md-block d-lg-none" />
        </p>
      </div>
      <div class="col-md-4 col-lg-3 mt-4 mt-lg-8 text-center text-md-start">
        <div class="badge bg-soft-danger p-3 rounded-3">
          <img class="w-100 h-100" src="{% static 'assets/img/icons/cloud.svg' %}" alt="..." />
        </div>
        <h4 class="mt-5 mb-3 fw-bold">Storing at the cloud</h4>
        <p class="fs-1 lh-sm">
          The application is using advanced Cloud Application
          <br class="d-none d-md-block d-lg-none" />
        </p>
      </div>
    </div>
  </div>
  <!-- end of .container-->
</section>
{% endblock content %}

EZBook/ezbook_client/templates/ezbook_client/footer.html
<section>
  <div class="container">
    <div class="row justify-content-lg-between circle-blend-right circle-danger">
      <hr class="text-200 mb-0" />
      <div class="row justify-content-md-center justify-content-evenly py-3">
        <div class="col-12 col-sm-8 col-md-6 col-lg-auto text-center text-md-start">
          <p class="fs-0 my-2 text-400">
            All rights Reserved 2021
            <span class="fw-bold text-500">
              &copy; Gary Lloyd Senoc | Adrian Vincent Aguilar CSIT327 F1-C1 AY 2021 - 2022
            </span>
          </p>
        </div>
        <div class="text-center">
          <a class="fs-0 my-2 text-400" href="{% url 'ezbook_admin:index' %}">
            EZBook Admin
          </a>
        </div>
      </div>
    </div>
    <!-- end of .container-->
</section>

EZBook/ezbook_client/templates/ezbook_client/home.html
{% extends "ezbook_client/base.html" %} {% load static %} {% block content %}
<section id="home">
  <div class="container">
    <div class="row align-items-center g-2">
      <div class="col-md-5 col-lg-6 order-0 order-md-1 text-end">
        <img class="pt-7 pt-md-0 w-100" src="{% static 'assets/img/gallery/hero-header.gif' %}" alt="hero-header" />
      </div>
      <div class="col-md-7 col-lg-6 py-6 text-md-start text-center">
        <h1 class="fw-bold fs-4 fs-lg-6 fs-xxl-7 text-primary">
          The platform for<br />
          better VAN and BUS BOOKING
        </h1>
        <p class="mb-5 fs-1 fw-medium">
          Book now with less hassle and paper-free
        </p>
        <a class="btn hover-top btn-collab" href="{% url 'ezbook_client:signin' %}"><i class="fas fa-download me-2"></i>
          Sign in</a><a class="btn hover-top btn-collab-outline text-gradient ms-2"
          href="{% url 'ezbook_client:register' %}">
          <i class="fas fa-play text-danger me-md-2 me-0"></i>Register</a>
      </div>
    </div>
  </div>
</section>

<!-- <section> close ============================-->
<!-- ============================================-->

<!-- ============================================-->
<!-- <section> begin ============================-->
<section class="py-6">
  <div class="container">
    <div class="row flex-center">
      <div class="col-md-4 col-lg-3 mt-4 mt-lg-8 text-center text-md-start">
        <div class="badge bg-soft-danger p-3 rounded-3">
          <img class="w-100 h-100" src="{% static 'assets/img/icons/edit.svg' %}" alt="..." />
        </div>
        <h4 class="mt-5 mb-3 fw-bold">Instant Booking</h4>
        <p class="fs-1 lh-sm">Book Anytime, Anywhere</p>
      </div>
      <div class="col-md-4 col-lg-3 mt-4 mt-lg-8 text-center text-md-start">
        <div class="badge bg-soft-danger p-3 rounded-3">
          <img class="w-100 h-100" src="{% static 'assets/img/icons/monitor.svg' %}" alt="..." />
        </div>
        <h4 class="mt-5 mb-3 fw-bold">Easy access</h4>
        <p class="fs-1 lh-sm">
          Can easily access different travel destinations<br class="d-none d-md-block d-lg-none" />
        </p>
      </div>
      <div class="col-md-4 col-lg-3 mt-4 mt-lg-8 text-center text-md-start">
        <div class="badge bg-soft-danger p-3 rounded-3">
          <img class="w-100 h-100" src="{% static 'assets/img/icons/cloud.svg' %}" alt="..." />
        </div>
        <h4 class="mt-5 mb-3 fw-bold">Storing at the cloud</h4>
        <p class="fs-1 lh-sm">
          The application is using advanced Cloud Application
          <br class="d-none d-md-block d-lg-none" />
        </p>
      </div>
    </div>
  </div>
  <!-- end of .container-->
</section>
<!-- <section> close ============================-->
<!-- ============================================-->

<!-- ============================================-->
<!-- <section> begin ============================-->

<!-- <section> close ============================-->
<!-- ============================================-->

<!-- ============================================-->
<!-- <section> begin ============================-->

<!-- <section> close ============================-->
<!-- ============================================-->

<!-- ============================================-->
<!-- <section> begin ============================-->

<!-- <section> close ============================-->
<!-- ============================================-->

<!-- ============================================-->
<!-- <section> begin ============================-->
<section class="pb-md-10" id="faq">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 col-lg-6 text-center mb-3">
        <h6 class="fw-bold fs-4 display-3 lh-sm mb-5">
          Frequently asked questions
        </h6>
      </div>
    </div>
    <div class="row flex-center">
      <div class="col-lg-9">
        <div class="accordion" id="accordionExample">
          <div class="accordion-item border-top">
            <h2 class="accordion-header" id="heading1">
              <button class="accordion-button px-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1"
                aria-expanded="true" aria-controls="collapse1">
                <span class="mb-0 fw-bold text-start fs-1 text-1000">Who should use the app?</span>
              </button>
            </h2>
            <div class="accordion-collapse collapse show" id="collapse1" aria-labelledby="heading1"
              data-bs-parent="#accordionExample">
              <div class="accordion-body pt-0 px-2">
                All our users like the amazing features and illustration of our
                app and it effective working procedure. Most of them are highly
                satisfied with our support and collaboration ideas which are
                counted as quite an essential in the tech business. With a team
                of highly creative and lively developers and manager, all our
                issues are promised to be solved in no time at all.
              </div>
            </div>
          </div>
          <div class="accordion-item border-top">
            <h2 class="accordion-header" id="heading2">
              <button class="accordion-button px-2 collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapse2" aria-expanded="true" aria-controls="collapse2">
                <span class="mb-0 fw-bold text-start fs-1 text-1000">What is the working procedure of the app?</span>
              </button>
            </h2>
            <div class="accordion-collapse collapse" id="collapse2" aria-labelledby="heading2"
              data-bs-parent="#accordionExample">
              <div class="accordion-body pt-0 px-2">
                You can issue either partial or full refunds. There are no fees
                to refund a charge, but the fees from the original charge are
                not returned.
              </div>
            </div>
          </div>
          <div class="accordion-item border-top">
            <h2 class="accordion-header" id="heading3">
              <button class="accordion-button px-2 collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapse3" aria-expanded="true" aria-controls="collapse3">
                <span class="mb-0 fw-bold text-start fs-1 text-1000">How is the app helpful?</span>
              </button>
            </h2>
            <div class="accordion-collapse collapse" id="collapse3" aria-labelledby="heading3"
              data-bs-parent="#accordionExample">
              <div class="accordion-body pt-0 px-2">
                Disputed payments (also known as chargebacks) incur a $15.00
                fee. If the customer’s bank resolves the dispute in your favor,
                the fee is fully refunded.
              </div>
            </div>
          </div>
          <div class="accordion-item border-top">
            <h2 class="accordion-header" id="heading4">
              <button class="accordion-button px-2 collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapse4" aria-expanded="true" aria-controls="collapse4">
                <span class="mb-0 fw-bold text-start fs-1 text-1000">Is the app workable while you got no
                  internet?</span>
              </button>
            </h2>
            <div class="accordion-collapse collapse" id="collapse4" aria-labelledby="heading4"
              data-bs-parent="#accordionExample">
              <div class="accordion-body pt-0 px-2">
                There are no additional fees for using our mobile SDKs or to
                accept payments using consumer wallets like Apple Pay or Google
                Pay.
              </div>
            </div>
          </div>
          <div class="accordion-item border-top">
            <h2 class="accordion-header" id="heading5">
              <button class="accordion-button px-2 collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapse5" aria-expanded="true" aria-controls="collapse5">
                <span class="mb-0 fw-bold text-start fs-1 text-1000">What are the security measure of the app?</span>
              </button>
            </h2>
            <div class="accordion-collapse collapse" id="collapse5" aria-labelledby="heading5"
              data-bs-parent="#accordionExample">
              <div class="accordion-body pt-0 px-2">
                There are no additional fees for using our mobile SDKs or to
                accept payments using consumer wallets like Apple Pay or Google
                Pay.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end of .container-->
</section>
{% endblock content %}

EZBook/ezbook_client/templates/ezbook_client/register.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Signin Template for Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/" />
  <!-- Bootstrap core CSS -->
  <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="https://getbootstrap.com/docs/4.0/examples/sign-in/signin.css" rel="stylesheet" />
</head>

<body class="text-center">
  <form class="form-signin">
    <h1>EZBook</h1>
    <h2 class="h3 mb-3 font-weight-normal">Register now</h2>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus />
    <label for="inputEmail" class="sr-only">Full name</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="Full name" required autofocus />
    <label for="inputEmail" class="sr-only">Phone number</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="Phone number" required autofocus />
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required />
    <div class="checkbox mb-3"></div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">
      Register
    </button>
    <p class="mt-5 mb-3 text-muted">&copy; 2021</p>
  </form>
</body>

</html>

EZBook/ezbook_client/templates/ezbook_client/signin.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Signin Template for Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/" />

  <!-- Bootstrap core CSS -->
  <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="https://getbootstrap.com/docs/4.0/examples/sign-in/signin.css" rel="stylesheet" />
</head>

<body class="text-center">
  <form class="form-signin">
    <h1>EZBook</h1>
    <h2 class="h3 mb-3 font-weight-normal">Please sign in</h2>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus />
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Password" required />
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me" /> Remember me
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">
      Sign in
    </button>
    <p class="mt-5 mb-3 text-muted">&copy; 2021</p>
  </form>
</body>

</html>